### ISSUE TITLE
[advice] bat  --style=plain

### ISSUE THREAD

**Issue by Freed-Wu** [wofr06/lesspipe.sh#102]
I notice `bat --style=plain` be used in `lesspipe.sh`. Why not provide a configure method such as environment variable or config file to allow user `bat` not `--style = plain`? I think many people prefer using `bat` to see line number and file header.

Thanks.

**Comment by wofr06** [comment]
A style can now be given to bat by setting the ENV variable `BAT_STYLE` or adding the option `--style=xxx` to the ENV variable `LESSCOLORIZER`. The default style remains 'plain'

**Comment by Freed-Wu** [comment]
In fact, bat has a config named `~/.config/bat/config`. So I advise to use bat's config as its default setting and only use `$LESSCOLORIZE` to override user's default config.

```
To set a default style, add the '--style=".."' option to the configuration file or export
              the BAT_STYLE environment variable
```

**Comment by Freed-Wu** [comment]
How about #105 #106 #107 #109 #110 #111 @wofr06
