### ISSUE TITLE
[feature] can user customize content line?

### ISSUE THREAD

**Issue by Freed-Wu** [wofr06/lesspipe.sh#104]
```sh
contentline () {
	declare a="==================================="
	echo "$a Contents $a"
}
```

Any environment variable or other method? Such as before lesspipe.sh's main program, source a user's shell script like `~/.config/lesspipe.sh`, then user can define their `contentline()` to override this function. I want to define some cooler contentline :smile:

Thanks!

**Comment by wofr06** [comment]
This function is called for rpm or deb archives (and iso images). Depending on the OS you will usually have only one of the types of files to display its contents. If you really dislike the `contentline` function, you could recode the interpretation of rpm or deb archives in a `.lessfilter` file and change the output to your liking. Sourcing unknown files at the beginning leaves too much room for abuse or introducing security problems.
