### ISSUE TITLE
How about use hr to generate pdf page break?

### ISSUE THREAD

**Issue by Freed-Wu** [wofr06/lesspipe.sh#108]
Now:

![Screenshot from 2022-10-21 00-19-59](https://user-images.githubusercontent.com/32936898/197004173-756e1922-0b43-499d-846e-fc1152d75088.png)

After I change:

![Screenshot from 2022-10-21 00-20-06](https://user-images.githubusercontent.com/32936898/197004214-e92668b3-0d30-4328-ae04-21d1af728c55.png)

I think the latter is better.

How can I add `|` to `$cmd`?

**Comment by wofr06** [comment]
Given that hr is not installed by default (in Ubuntu) and the minor improvement it makes I tend to not implement that change
