### ISSUE TITLE
code2color: support pygmentize's guessing from input?

### ISSUE THREAD

**Issue by xuhdev** [wofr06/lesspipe.sh#11]
Sometimes when there is no file name, code2color seems not working any more. For example,

```
git diff | less
```

In this case, the output won't be colorized as a diff file. However, pygments has the ability to guess out. If you run

```
git diff | pygmentize | less
```

Everything's colorized. Is it possible to support this feature?

**Comment by wofr06** [comment]
On Sun, 25 Sep 2016, Hong Xu wrote:

> Sometimes when there is no file name, code2color seems not working any more. For example,
> 
> git diff | less
> 
> In this case, the output won't be colorized as a diff file. However, pygments has the ability to guess out. If you run
> 
> git diff | pygmentize | less
> 
> Everything's colorized. Is it possible to support this feature?

Dear Hong Xu,

in principle yes. In the man page of less you can find the following 
statement:

For compatibility with previous versions of less, the input preprocessor 
or pipe is not used if less is viewing standard input. However, if the 
first character of LESSOPEN is a dash (-), the  input preprocessor is 
used on standard input as well as other files. In this case, the dash is 
not considered to be part of the preprocessor command.

As this is however an addition done after lesspipe was designed, lesspipe 
does not always handle the input correctly when using a minus sign as the 
first character in the LESSOPEN env variable. I do have however plans to 
handle both '-' and '|-' properly as described in the man page of less.

According to my plans this will happen not really soon but I guess 
somewhen during the coming months it could be doable.

The main problem is that I am guessing the type of files by reading the 
first part of the file and then afterwards I start reading again from the 
beginning to display the file contents. To make this work in a pipe this 
piece of code would have to be changed.

## 

Best reggards
Wolfgang Friebel                   Deutsches Elektronen-Synchrotron DESY
Phone/Fax:  +49 33762 77372/216    Platanenallee 6
Mail: Wolfgang.Friebel AT desy.de  D-15738 Zeuthen  Germany

**Comment by wofr06** [comment]
With the latest version the diff example is now working, but certainly not all cases can be covered equally well. For such situations a :type appended to the file name can force the proper colorization.
