### ISSUE TITLE
glow and lesspipe: no color and bad rendering

### ISSUE THREAD

**Issue by mathomp4** [wofr06/lesspipe.sh#112]
I recently discovered [glow](https://github.com/charmbracelet/glow) by @charmbracelet as a Markdown renderer, and I like it even more than mdcat. So, much like I did with mdcat before, I made up a `~/.lessfilter`:

```
❯ less ~/.lessfilter
#!/usr/bin/env bash

if [[ "$1" = *.md ]]; then
   glow $1
   exit 0
fi
exit 1
```

but something when in combo with `lesspipe` seems tombreak it. For example, here is a README.md rendered by `glow`:

<img width="1642" alt="Screen Shot 2022-11-14 at 8 19 09 AM" src="https://user-images.githubusercontent.com/2982494/201670247-054f2a91-dbac-46b9-bd8d-cf62bb22d96e.png">

but when I use `less`:

<img width="1642" alt="Screen Shot 2022-11-14 at 8 19 30 AM" src="https://user-images.githubusercontent.com/2982494/201670315-d471a08f-3f89-4fff-9085-cf2c0341ea1d.png">

So it's like some of the things `glow` does are suppressed. Not everything as the tables do still have some of that nice ASCII line art, but colors are gone and spacing seem off.

If I add an echo to my `~/.lessfilter` I do see the echo, so `glow` is called.

Any ideas? My `LESS` vars are:
```
LESS=-fRimWFX
LESSOPEN=|/Users/mathomp4/.homebrew/brew/bin/lesspipe.sh %s
LESSANSIMIDCHARS=0123456789;[?\'#%()*+ SetMark
```
The `LESSANSIMIDCHARS` came from [#48 via @anaraven](https://github.com/wofr06/lesspipe/issues/48#issuecomment-996063151). In case that was the issue, I  `unset` them, but it didn't change anything.

**Comment by wofr06** [comment]
The weird behaviour comes from the fact, that glow is here called inside of a pipe, where the terminal characteristics cannot be queried. Usually the style is set automatically to "light" or "dark". This fails here and there is obviously no fallback. You have to call glow either with `glow -s dark` or `glow -s light`. Alternatively cou can set a default in the config file of glow with `glow config`

**Comment by mathomp4** [comment]
@wofr06 Thanks! I kept staring at the lesspipe code thinking "I see no reason" but never thought about the style!

But since I am always on a dark terminal, I've belt-and-suspendered it and made it dark everywhere. 😄
