### ISSUE TITLE
Colorizing links with `mdcat` broken

### ISSUE THREAD

**Issue by treyharris** [wofr06/lesspipe.sh#119]
Given the input file `TEST.md`:

```markdown
# Testing `lspipe` and `mdcat`

Things like _italics_ and **bold** work great.

## As do heads
### And subheads

But strangely [links](https://example.com) do not, in
- [any](https://google.com)
- [context](https://github.com/wofr06/lesspipe/)
- but raw URL's like https://github.com/swsnr/mdcat work.

A [local](link) link doesn't work better either.
```

I get the following results (`lesspipe.sh` above and raw `mdcat` below):
![IMG_2704](https://user-images.githubusercontent.com/97895/207979665-639ecdf2-d927-45ae-8999-bb8755ac950c.jpeg)

Note that I’m using the same version of `mdcat` (https://github.com/swsnr/mdcat, previously https://github.com/lunaryorn/mdcat) you mentioned using in other issues.

This happens regardless of ssh or mosh, tmux or non-tmux. (I don’t have GUI access so I’m not sure how it would look there.) My `TERM` is `xterm-256color` or `screen-256color`, on Ubuntu 20 LTS, on the newest release of `mdcat`.

Thanks—`lesspipe.sh` has been indispensible to me!

**Comment by wofr06** [comment]
With the given input the misbehaviour of lesspipe as documented above could not be reproduced.
