### ISSUE TITLE
macOS bash compatibility

### ISSUE THREAD

**Issue by muneebmahmed** [wofr06/lesspipe.sh#121]
Using the default bash environment of this script gives this error on macOS:
```
/usr/local/bin/lesspipe.sh: line 398: typeset: -l: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
```
This is due to macOS's outdated bash 3.2 which can't be updated, and doesn't support the `-l` option used here: https://github.com/wofr06/lesspipe/blob/a24c496dd1d820795be8ddc624d65d8504fb5dab/lesspipe.sh#L398

This can be worked around by using zsh and passing `--shell /bin/zsh` to the configure script, or to install an up-to-date bash and place it ahead of default bash in the `PATH`

We could also just replace this use of `typeset -l`, as suggested in this [PR in homebrew](https://github.com/Homebrew/homebrew-core/pull/120432). That argument seems to be converting the string in its initial assignment to lowercase. Could this be done with a call to `tr` instead?

**Comment by wofr06** [comment]
The fix in #122 was accepted
