### ISSUE TITLE
Colorizer doesn't turn on if raw flag is combined in LESS and not at the end

### ISSUE THREAD

**Issue by bgmonroe** [wofr06/lesspipe.sh#132]
If LESS is a concatenation of args (ie. LESS="-XRI") and the `R` flag does not come at the end of the string, the Colorizer will not turn on.  So `LESS="-RXI"` does not work, `LESS="-XRI"` also does not work, but `LESS="-XIR"` does work.

**Comment by wofr06** [comment]
Changed the test to correctly recognize the -R flag. In the unlikely case that $LESS contains options requiring an argument (e.g. a file name) and the argument contains both a minus sign and r or R, then the colorizer is turned on, which may not be intended.
