### ISSUE TITLE
SSH config files not properly identified with `bat`

### ISSUE THREAD

**Issue by muneebmahmed** [wofr06/lesspipe.sh#133]
Running `less ~/.ssh/config` does not apply any formatting, and writes this to stderr:
```
[bat error]: unknown syntax: 'config'
```

This worked correctly before commit [`d3d60c207f533169bfad7cb184a0ebdeb96a4b0c`](https://github.com/wofr06/lesspipe/commit/d3d60c207f533169bfad7cb184a0ebdeb96a4b0c); when using that commit, the error message is simply:
```
[bat error]: unknown syntax: ''
```
All subsequent commits give the first error above with `config`.

I've reproduced this on my other computer, both with macOS and have `bat` installed

**Comment by wofr06** [comment]
Determining the file extension and comparing it against available languages for bat has been improved.
