### ISSUE TITLE
Broken paths in generated Makefile 

### ISSUE THREAD

**Issue by Schamschula** [wofr06/lesspipe.sh#138]
As I was updating the MacPorts Portfile to `lesspipe` v2.10, I ran into an issue:

```
cp ./less_completion /opt/local/share/bash-completion
cp: /opt/local/share/bash-completion/less_completion: Operation not permitted
make: *** [install] Error 1
```

Upon further investigation I found that the path was incomplete.

See: https://github.com/macports/macports-ports/commit/9db1296765805f1ec39c84d20a9efc2ee6e36306#diff-0486be860a9733caee13c31b1bd57b7a78517a779a5727defd092610bc6fae44

**Comment by wofr06** [comment]
I changed the configure script and do different things whether the prefix is set or not. Please give it a try. The better option would be to always install in /etc/bashcompletions.d, at least on Ubuntu.
