### ISSUE TITLE
support org file format

### ISSUE THREAD

**Issue by KiaraGrouwstra** [wofr06/lesspipe.sh#139]
org is a markup format popularized by emacs' [Org Mode](https://orgmode.org/) plugin.
it would be nice to get support for this format in lesspipe as well.
it looks like [pandoc](https://pandoc.org/org.html) might help achieve this.

**Comment by wofr06** [comment]
When viewing an org file using the current version of lesspipe there is not much difference to the output of  `pandoc --from=org` . Given the similarity to the commonly used newer markdown formats and the infrequent use of the org markup format I would recommend not implementing it. You could implement it privately by using a .lessfilter file.
