### ISSUE TITLE
Add support for lz4 compression

### ISSUE THREAD

**Issue by pstibrany** [wofr06/lesspipe.sh#14]
Files with .lz4 extension can be decompressed using lz4 -dc or lz4cat. Thanks.

**Comment by vaeth** [comment]
See this pull request https://github.com/wofr06/lesspipe/pull/16

**Comment by bbigras** [comment]
The pull request was merged. Can this issue be closed now?

**Comment by pstibrany** [comment]
Sure, thanks!
