### ISSUE TITLE
support jaq as an alternative to jq

### ISSUE THREAD

**Issue by KiaraGrouwstra** [wofr06/lesspipe.sh#145]
[jaq](https://github.com/01mf02/jaq) is a rust port of `jq`, although they by default only export a `jq` binary rather than aliasing this to `jq` as well.
it would be nice if lesspipe were to support using this package as an alternative to `jq` as well.

**Comment by wofr06** [comment]
The jq binary is available for several Linux distros but packages for jaq are rare. Even then jq could be installed alongside to jaq (or aliased to jq). I do not see a benefit for adding the support for jaq. It is a very small change but I tend to keep the number of external programs supported at a reasonable minimum in order avoiding to check compatibilities, vulnerabilities etc.
Other opinions?
