### ISSUE TITLE
support unrar-free

### ISSUE THREAD

**Issue by KiaraGrouwstra** [wofr06/lesspipe.sh#146]
[`unrar-free`](https://gitlab.com/bgermann/unrar-free) is an open-source alternative to the proprietary `rar` and `unrar`.they by default only export an `unrar-free` binary rather than aliasing this to `unrar` as well.
it would be nice if lesspipe were to support using this package as an alternative to `rar` / `unrar` / `bsdtar` as well.

**Comment by wofr06** [comment]
The rar format is nowadays not to often used, mostly on Windows computers and none of the installations I have access to have rar/unrar/bsdtar installed. My guess is that the display of rar formatted files within less is not widely used and for those few cases where users want it, they tend to install one of the available supported alternatives to unrar-free themselves. System wide installations of rar and friends in computer centers are uncommon.  To keep the number of external programs small, that are used in lesspipe, I tend to not add unrar-free. Other opinions?
