### ISSUE TITLE
Bat theme name with spaces not handled

### ISSUE THREAD

**Issue by smallid** [wofr06/lesspipe.sh#151]
Bat includes themes that have spaces in the name (as reported by `bat --list-themes`), for example I have set a default `bat` theme of `BAT_THEME=Solarized (light)`. `lesspipe.sh` appears to truncate the theme name at the first space, which results in bat not using the specified theme and giving a warning like:
`[bat warning]: Unknown theme 'Solarized', using default.`

When I use a bat theme without a space in the name, it works.

For example:
```
# works
> BAT_THEME="ansi" less temp.txt

# does not work
> BAT_THEME="Solarized (light)" less temp.txt
[bat warning]: Unknown theme 'Solarized', using default.
```

It looks like maybe `${theme%% *}` only prints out the variable to the first space?
https://github.com/wofr06/lesspipe/blob/99f9d983b3839c045d4bfb141502b6a7d34f6629/lesspipe.sh#L451

**Comment by wofr06** [comment]
Thanks, corrected. I also changed the preferences for the bat style/theme values. The contents of the LESSCOLORIZER string takes precedence, next come the  ENV variables BAT_XXX. Only then options from the config file get respected.
