### ISSUE TITLE
Does not work with dotfiles

### ISSUE THREAD

**Issue by SnoringFrog** [wofr06/lesspipe.sh#154]
lesspipe fails for files like .gitconfig and .bashrc

I was trying to find a solution that didn't require specifically supporting individual dotfile names. Pygmentize's guess option figures out what they are, so I feel like there's a way, but I didn't look into how pygmentize handles it (sidenote, along the way I found I could append ':g' to the filename to use pygmentize's guess, so that works around this issue for me perfectly fine).

I did get it working by changing lesspipe.sh:13 to `.*) extension=${fn##*.} ;;` but considering that makes that function useless, I suspect that breaks something. I ran test.pl to check, but I get mostly failures even with an unmodified lesspipe.sh. For what it's worth, the passed/ignored/failed numbers are the same both with and without the change (0/45/79), but I didn't trust that enough to make this a PR rather than an Issue.

**Comment by wofr06** [comment]
I changed line 14 instead and added a test in the test suite. It works now both for `bat`, `pygmentize` and `vimcolor`.  The test file `.gitconfig` in `special.tgz` is not a valid gitconfig file and does not get colored with `pygmentize`. The test suite runs for me without failures, if  `LESS=-R`  is not present and  most dependencies are installed.
