### ISSUE TITLE
How to specify bat theme with spaces in LESSCOLORIZER

### ISSUE THREAD

**Issue by mathomp4** [wofr06/lesspipe.sh#160]
I did a search and found #151 so I'm guessing themes with spaces should be allowed. But I only seem to be able to enable them in my `.zshenv` by using `BAT_THEME`. If I have:

```zsh
export BAT_THEME="Monokai Extended Bright"
export LESSCOLORIZER='bat --style=plain --color=always'
export LESSOPEN="|$BREWPATH/bin/lesspipe.sh %s"
```

then `lesspipe` provides me with output that is `bat` the style and theme I expect. But if I instead do:

```zsh
export LESSCOLORIZER='bat --style=plain --color=always --theme="Monokai Extended Bright"'
export LESSOPEN="|$BREWPATH/bin/lesspipe.sh %s"
```

It doesn't pick up on the theme.

If I try a theme without a space (like `DarkNeon`) that is reflected. So, perhaps do I need to escape spaces?

**Comment by wofr06** [comment]
The `LESSCOLORIZER` string is already quoted and currently additional quoting is not removed. I will consider removing additional quoting. Until then as a workaround  themes with spaces can be specified by omitting the double quotes in the example above AND the theme option has to be the last option such as 
`export LESSCOLORIZER='bat --style=plain --color=always --theme=Monokai Extended Bright'`

**Comment by mathomp4** [comment]
Ohhh. Well I feel dumb.  I think I tried every combo of quoting and escaping except that.

It works! Closing.

**Comment by wofr06** [comment]
The parsing of `LESSCOLORIZER` is now improved and the workaround is no longer required
