### ISSUE TITLE
Bug when handling xlsx files

### ISSUE THREAD

**Issue by harkabeeparolus** [wofr06/lesspipe.sh#161]
> There is a bug that was introduced here.
> 
> * `in2csv -f xlsx` has been changed to `xls` instead. This fails on basically every xlsx file.
> 
> * Testing for the command `excel2csv`but running `xls2csv`.
> 
> Seems like a simple copy-paste error from the "ms-excel" section below. 

 _Originally posted by @harkabeeparolus in [922f043](https://github.com/wofr06/lesspipe/commit/922f0434db793527ed893ef149fdf4097273cf8f#r150101701)_

**Comment by wofr06** [comment]
Indeed. Thanks, both lines wrongly copied are corrected now.
