### ISSUE TITLE
Invalid option when calling lesspipe on Mac

### ISSUE THREAD

**Issue by chuckn246** [wofr06/lesspipe.sh#162]
Recently noticed an error when calling `lesspipe` on Mac running Sequoia 15.2 and another Mac running Sonoma.

```bash
$ less README.md 
/Users/user/.local/bin/lesspipe.sh: line 844: declare: -l: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

Unfortunately, Bash on Mac is pretty old:
```bash
$ bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin24)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Maybe [commit d2df6fe](https://github.com/wofr06/lesspipe/commit/d2df6fe0e35102d302f5fb9a302c27b40c0ffd2f#diff-1d1c7e00b6f9694b32709c3c2f27ce31a59fb99df5ebfd476c5b93206bd3c329R846) introduced the error with the `declare -l` call?

**Comment by wofr06** [comment]
converting content of variable to lowercase changed back to using tr.

**Comment by chuckn246** [comment]
Just updated and tested.
Looks good on my end -- thanks for the quick fix!
