### ISSUE TITLE
I can't make it work on Linux.

### ISSUE THREAD

**Issue by bouncydot** [wofr06/lesspipe.sh#17]
Hello,

I use ubuntu 16.04 and Linux Mint. I really cannot make _lesspipe_ and _code2color_ work on one of my systems.

I have followed your installing instructions 100%. It might be totally irrevelant but when I type: `echo $LESSOPEN` it displays `| /usr/bin/lesspipe %s` instead of `LESSOPEN="|/usr/local/bin/lesspipe.sh %s"` where I actually moved the files to and how I set the LESSOPEN variable. No matter where I save or delete the variable assignment the output stays the same.

Could this be the reason and what could I do to resolve it?  

Thank you!

**Comment by wofr06** [comment]
Hi,
please look into your shell environment. The LESSOPEN variable is probably set in one of the shell initialization files and overwrites always your assignment.
To  temporarily try the newly installed lesspipe.sh you can put the LESSOPEN assignment in front of the less command such as e.g.

LESSOPEN="|/usr/local/bin/lesspipe.sh %s" less filename
