### ISSUE TITLE
Ability to disable helpful hints in output

### ISSUE THREAD

**Issue by HaleTom** [wofr06/lesspipe.sh#21]
Currently I see hints such as:

```
$ lesspipe.sh tmp/z.gz: 
==> append :. or :<filetype> to activate syntax highlighting
...
```

I'm trying to get rid of these.

My current workaround is to use:
```
$ LESS= lesspipe.sh tmp/z.gz
```

But this disables syntax highlighting.

Could these "helpful" messages be silenced, perhaps by default or with a command line option?

**Comment by wofr06** [comment]
Dear Tom,
silencing the "helpful" messages is already built in, you can set the ENV variable LESSQUIET to 1 to achieve this, e.g. 

LESSQUIET=1 less tmp/z.gz

This is also documented in my lesspipe.1 man page:

To suppress informal messages in the first line of  the  filter  output the ENV variable LESSQUIET can be set to a nonempty value.

Cheers, Wolfgang
