### ISSUE TITLE
Add support for ~/.lessfilter (like on Debian)

### ISSUE THREAD

**Issue by alexbarton** [wofr06/lesspipe.sh#23]
The `lesspipe` command in Debian linux supports user-specific overrieds using a `~/.lessfilter` executable (scrip). Excerpt from the [`lesspipe`(1) Debian manual page](https://manpages.debian.org/stretch/less/lesspipe.1.en.html#USER_DEFINED_FILTERS):

    USER DEFINED FILTERS
       It  is  possible to extend and overwrite the default lesspipe and less‐
       file input processor if you have specialized  requirements.  Create  an
       executable  program with the name .lessfilter and put it into your home
       directory. This can be a shell script or a binary program.

       It is important that this program returns the correct exit code: return
       0  if  your  filter  handles  the  input,  return  1  if  the  standard
       lesspipe/lessfile filter should handle the input.

It would be great to have this functionality in this project as well!

What do you think?

**Comment by wofr06** [comment]
Just added the functionality in git
