### ISSUE TITLE
export xls(x) and ppt(x) files as html

### ISSUE THREAD

**Issue by Konfekt** [wofr06/lesspipe.sh#26]
When `Libreoffice` converts `xls(x)` or `ppt(x)` files, results are better when the output is HTML instead of plain text. For this, converting `name.ext` a temp file `/tmp/name.html` will be created by passing the parameter `--outdir /tmp` to libreoffice and then piped to a terminal browser.  See https://github.com/Konfekt/vim-office/blob/53bc54410463f9adc418ec524e3e23d0dcaaa9bb/ftdetect/office.vim#L135

This is to improve on https://github.com/wofr06/lesspipe/pull/24.

**Comment by Konfekt** [comment]
This has now been included in 5c36b2b977928c78ddbd6385db696b6fe2e380dc, albeit not making use of `istemp`.

**Comment by wofr06** [comment]
for xls(x) and ppt(x) files the fallback is now libreoffice converting to html, then html to text
