### ISSUE TITLE
remove one of lesspipe.sh or lesspipe.sh.in

### ISSUE THREAD

**Issue by Konfekt** [wofr06/lesspipe.sh#28]
How about removing `lesspipe.sh` as generated code should not be version controlled. 

Instead, running `./config --default=yes` could be mentioned in the README and install instructions. Distributions could ship with it, or a downloadable versioned release, a simple script, could be made available.

Alternatively, `./configure` and `lesspipe.sh.in` could be dropped and `lesspipe.sh` kept, as reconfiguring the executable after every  installation of a supported converter is unnecessary, if the existence of the executables is checked anyway for every filetype. That is, `lesspipe.sh` generated by `./configure --yes` could be kept.

**Comment by Konfekt** [comment]
The latest release 1.83 at https://github.com/wofr06/lesspipe/releases is such an attempt. To make things simple, the automatic release of source code after a commit could be disabled; perhaps this is due to automatic tagging? If so, then this would mean manual tagging.

**Comment by wofr06** [comment]
lesspipe.sh.in is no longer in use
