### ISSUE TITLE
Add support for GNU Source-highlight

### ISSUE THREAD

**Issue by PierreTechoueyres** [wofr06/lesspipe.sh#3]
Could you provide support for GNU Source-highlight (http://www.gnu.org/software/src-highlite/) ?

I think this quick (and dirty) patch could do the trick

``` shell
1 file changed, 25 insertions(+)
lesspipe.sh.in | 25 +++++++++++++++++++++++++

modified   lesspipe.sh.in
@@ -560,6 +560,18 @@ isfinal() {
       lang=${3#$sep}
       lang="-l ${lang#.}"
       lang=${lang%%-l }
+      if cmd_exist source-highlight; then
+     case "$2" in
+         *ChangeLog|*changelog)
+         source-highlight --failsafe -f esc --lang-def=changelog.lang --style-file=esc.style -i "$2"
+         ;;
+         *Makefile|*makefile)
+         source-highlight --failsafe -f esc --lang-def=makefile.lang --style-file=esc.style -i "$2"
+         ;;
+         *)
+         source-highlight --failsafe -f esc --lang-def=${lang}.lang  --style-file=esc.style -i "$2"
+     esac
+      fi
       if cmd_exist code2color; then
         code2color $PPID ${in_file:+"$in_file"} $lang "$2"
         if [[ $? = 0 ]]; then
@@ -990,6 +1002,19 @@ isfinal() {
 # the next conditional is only there to remove syntax highlighting code
 #ifdef perl
   if [[ "$1" = *plain\ text* ]]; then
+    if cmd_exist source-highlight; then
+      case "$2" in
+   *ChangeLog|*changelog)
+     source-highlight --failsafe -f esc --lang-def=changelog.lang --style-file=esc.style -i "$2"
+     ;;
+   *Makefile|*makefile)
+       source-highlight --failsafe -f esc --lang-def=makefile.lang --style-file=esc.style -i "$2"
+       ;;
+   *)
+       source-highlight --failsafe -f esc --infer-lang --style-file=esc.style -i "$2"
+      esac
+      return
+    fi
     if cmd_exist code2color; then
       code2color $PPID ${in_file:+"$in_file"} "$2"
       if [[ $? = 0 ]]; then
```

**Comment by wofr06** [comment]
On Sat, 14 Nov 2015, Pierre Téchoueyres wrote:

> Could you provide support for GNU Source-highlight (http://www.gnu.org/software/src-highlite/) ?

Dear Pierre,

many thanks for your contribution. It looks like this construct could work 
as is. However if you look at the code2color script you will see that I 
did move the highligting support for pygmentize already to that script. As 
there are potentially even more colorizers (your proposed 
source-highlight, another program highlight available e.g. on Ubuntu) I 
would like to handle all of it in the code2color script. There is some 
code in that script to prevent calling colorizers if less cannot handle 
its output properly.

Alternatively I could have support for all the colorizers in lesspipe.sh. 
The advantage would be that then the installation of code2color would be 
optional, if people go for other highlighting solutions. Then the 
protection code in code2color would simply be ignored like in your patch 
below.

I am yet undecided. I will try to both include source-highlight and 
highlight as alternate colorizers.

Did you know that vim can be put into a mode that does syntax highlighting 
and more or less acting like less:

In the vim installations there is a macros/less.sh and macros/less.vim 
which do that.

Do you have any opinion abot the points I wrote?

Best regards
Wolfgang Friebel                   Deutsches Elektronen-Synchrotron DESY
Phone/Fax:  +49 33762 77372/216    Platanenallee 6
Mail: Wolfgang.Friebel AT desy.de  D-15738 Zeuthen  Germany

**Comment by PierreTechoueyres** [comment]
I really don't know what's the right way to do this.
Add an new entry for each code colorizer in `lesspipe.sh.in` could end up with a giant `case ... esac`. But it may be possible to refactor the code to do something smarter.
On the other side you can consider `code2color` as an common interface to multiple colorizers.
I haven't patched `code2color` not only because I don't know how to do this and also because of the check which only allow `pygmentize` use.

**Comment by wofr06** [comment]
source-highlight is now supported and according to my tests working
