### ISSUE TITLE
"text executable" files no longer display properly

### ISSUE THREAD

**Issue by nobu** [wofr06/lesspipe.sh#32]
By afd8a09501a2ad62aa1e83ea256c4d94476f9d1a moved the `[[ "$1" = *text\ executable* ]]` condition after `[[ "$1" = *executable* ]]` condition, script files with tabs/short lines no longer display properly.

**Comment by Konfekt** [comment]
Thank you pointing this out. Should be solved by b2c2bc3de0fb93a61e292e3d8e1606382d7684dd then.

**Comment by nobu** [comment]
Working fine now, thank you.
