### ISSUE TITLE
Syntax highlighting not available on text executables (shell scripts)

### ISSUE THREAD

**Issue by log2** [wofr06/lesspipe.sh#38]
While [https://github.com/wofr06/lesspipe/issues/32] was certainly useful to catch type of those files on macOS Catalina, i.e., "POSIX shell script text executable, ASCII text", syntax highlighting is still not available: I see just plain text.

To enable syntax highlighthing using 'code2color' I tried to substitute 

`cat "$2"`

with:

`set "plain text" "$2"`

(anticipation of the last case of if/elif chain)

This trick seems to work properly for me; I opened a PR with the change, see [https://github.com/wofr06/lesspipe/pull/39].

**Comment by laloch** [comment]
Hi, #39 doesn't solve the issue for me, because `filetype()` returns `"text"` for all MIME types with leading "text/".

**Comment by Konfekt** [comment]
This means that the additional clause

```sh
 elif [[ "$1" = "text" ]]; then
  set "plain text" "$2"
```

would solve the problem for you?

**Comment by laloch** [comment]
Well, technically yes, but I would rather like to know what the idea behind https://github.com/wofr06/lesspipe/blob/a263fb4b66438cbed8ee9cda8dab59809e7d615d/lesspipe.sh#L189-L191 was and perhaps see it go away. Such a generalization does not seem to make sense for text files.

**Comment by Konfekt** [comment]
Perhaps @wofr06 could answer this?

**Comment by wofr06** [comment]
Hi,

I have looked into that. I do not really remember what was the 
distinction between 'text' and 'plain text'.

As it looks the file type 'text' is nowhere tested and prevents calling 
code2color. Setting the file type from the mime type was thought as a 
last resort if the file command could not determine the type of the 
file. Setting it to 'plain text' is certainly o.k. assuming that all 
mime type text files could be tried for syntax highlighting.

However the real question is, why filetype did not yield a good answer 
for you. For shell scripts I do get e.g.

Bourne-Again shell script, ASCII text executable

If codecolor tries to colorize a file it does similar checks to 
determine the file type as the file command does. By renaming a bla.sh 
file to bla and by removing the shebang line also code2color does not 
colorize shell files. So I believe the change you are proposing is a 
hack, that probably is o.k. but the issue that 'file' does not give a 
good answer persists.

The idea behind lesspipe is, that it does not matter, what file suffix a 
file has. It tries to print a human readable content of the file based 
on what is in it. Therefore setting the file type based on the mime type 
is already a sign of lesspipe not correctly working (I believe).

If you could send me more details (OS used, the output of file -v, a 
short file where the problem occurs and how the LESS* variables are set) 
I could try to understand what happens.

Cheers, Wolfgang

Am 02.05.20 um 12:32 schrieb Enno:

**Comment by laloch** [comment]
> However the real question is, why filetype did not yield a good answer for you.

Because it's broken :wink:. See:
```
$ file blur.cpp
blur.cpp: C source, ASCII text
$ file -i blur.cpp
blur.cpp: text/x-c; charset=us-ascii
$ file blur.h
blur.h: C++ source, ASCII text
$ file -i blur.h
blur.h: text/x-c++; charset=us-ascii
$ file iommu.sh
iommu.sh: Bourne-Again shell script, ASCII text executable
$ file -i iommu.sh
iommu.sh: text/x-shellscript; charset=us-ascii
$ file setup.py
setup.py: Python script, ASCII text executable
$ file -i setup.py
setup.py: text/x-python; charset=us-ascii
$ file util.js
util.js: UTF-8 Unicode text
$ file -i util.js
util.js: text/plain; charset=utf-8
```

In all the above cases, except for the JavaScript, `file` yielded the correct answer. `filetype()`, however, is made to not acctept the result for most file formats and call `file -i` instead. The resulting MIME type (mostly "text/*" for text files) is then reduced to just "text" for some reason.

**Comment by laloch** [comment]
The problem is here: https://github.com/wofr06/lesspipe/blob/a263fb4b66438cbed8ee9cda8dab59809e7d615d/lesspipe.sh#L177-L190
You see? `filetype()` stores the result of `file` call in `$type` variable. It then does some corrections depending on specific `$file` values and stores the corrected string in `$return`. If the `$type`, however, passes through the cascaded `if` uncorrected, it gets just discarded.

Edit: Long story short, the issue is that `$return` in the above code is mostly undefined.

**Comment by laloch** [comment]
Run trace of `filetype` folows:
```
$ ./lesspipe.sh test.pl
++ typeset name
++ name=test.pl
++ [[ test.pl = - ]]
++ [[ test.pl = *.br ]]
++ [[ test.pl = *.bro ]]
++ [[ test.pl = *.tbr ]]
++ [[ test.pl = - ]]
++ typeset return
+++ filecmd test.pl
+++ file -L -s test.pl
+++ cut -d : -f 2-
+++ file -L -s -i test.pl
+++ sed -n 's/.*charset=/;/p'
+++ tr a-z A-Z
++ type=' Perl script text executable
;US-ASCII'
++ [[  Perl script text executable
;US-ASCII = \ \e\m\p\t\y ]]
++ [[  Perl script text executable
;US-ASCII = *OpenDocument\ Text* ]]
++ [[  Perl script text executable
;US-ASCII = *OpenDocument\ * ]]
++ [[  Perl script text executable
;US-ASCII = *OpenOffice\.org\ 1\.x\ * ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ Office\ Document* ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ Office\ Word* ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ Office\ Document* ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ Office\ PowerPoint* ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ Office\ Document* ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ Excel* ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ Office\ Document* ]]
++ [[  Perl script text executable
;US-ASCII = *Zip\ archive* ]]
++ [[  Perl script text executable
;US-ASCII = Microsoft\ OOXML ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ Word\ 2007* ]]
++ [[  Perl script text executable
;US-ASCII = *Zip\ archive* ]]
++ [[  Perl script text executable
;US-ASCII = Microsoft\ OOXML ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ PowerPoint\ 2007* ]]
++ [[  Perl script text executable
;US-ASCII = *Zip\ archive* ]]
++ [[  Perl script text executable
;US-ASCII = Microsoft\ OOXML ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ Excel\ 2007* ]]
++ [[  Perl script text executable
;US-ASCII = *Zip\ archive* ]]
++ [[  Perl script text executable
;US-ASCII = Microsoft\ OOXML ]]
++ [[  Perl script text executable
;US-ASCII = *Microsoft\ *\ 2007* ]]
++ [[  Perl script text executable
;US-ASCII = *MPEG\ *layer\ 3\ audio* ]]
++ [[  Perl script text executable
;US-ASCII = *MPEG\ *layer\ III* ]]
++ [[  Perl script text executable
;US-ASCII = *mp3\ file* ]]
++ [[  Perl script text executable
;US-ASCII = *MP3* ]]
++ [[  Perl script text executable
;US-ASCII != *lzip\ compressed* ]]
++ [[ test.pl = *.lzma ]]
++ [[ test.pl = *.tlz ]]
++ [[  Perl script text executable
;US-ASCII = *Zip* ]]
++ [[  Perl script text executable
;US-ASCII = *ZIP* ]]
++ [[  Perl script text executable
;US-ASCII = *Hierarchical\ Data\ Format* ]]
++ [[  Perl script text executable
;US-ASCII = *roff\ *,* ]]
++ [[  Perl script text executable
;US-ASCII = *HTML* ]]
++ [[  Perl script text executable
;US-ASCII = *ASCII* ]]
++ [[ test.pl = *xml ]]
++ [[  Perl script text executable
;US-ASCII = *XML* ]]
++ [[ -n '' ]]
+++ file -i test.pl
+++ cut -d : -f 2-
++ mime=' text/x-perl; charset=us-ascii'
++ [[  text/x-perl; charset=us-ascii = \ text/* ]]
++ return=text
++ [[ -n text ]]
++ echo text
++ set +x
```
