### ISSUE TITLE
Converting exported LANG to lowercase causes issues with perl and probably other programs

### ISSUE THREAD

**Issue by vaeth** [wofr06/lesspipe.sh#41]
commit d13c24786e7af2eecb10ebaeec811acbac8553af causes problems here:

If LANG is exported, converting LANG to lowercase breaks subsequent calls of e.g. perl (implicit through code2color), because LANG=c or LANG=de_de.utf-8 are not valid locale settings for perl.

The issue may become hidden if LC_ALL is exported, but this is not how locales should be used, in general.

A workaround might be to use a different variable name than LANG for the result

**Comment by Konfekt** [comment]
Going all lowercase is just one means of normalization. Would then going all upper case be a solution?

**Comment by wofr06** [comment]
Hi Enno,

no, changing the content of a widely used variable is not a good solution. Either you revert your latest change or accept the proposed change.
Cheers, Wolfgang

17.05.2020 20:30:12 Enno <notifications@github.com>:
