### ISSUE TITLE
Missing vim wiki entry

### ISSUE THREAD

**Issue by BachoSeven** [wofr06/lesspipe.sh#43]
Hi, I cannot find the actual instructions for vim integration in the README and this page  found in the wiki https://github.com/wofr06/lesspipe/wiki/snippet-to-read-unrecognized-files-through-lesspipe-in-Vim is empty

**Comment by Konfekt** [comment]
Thank you for pointing out the dead link. It was fixed now. Please check again. Also, you might want to have a look at my plug-in [vim-office](https://github.com/konfekt/vim-office).

**Comment by BachoSeven** [comment]
Thanks, this is very helpful, I always wanted to have a unified way to open various docs in vim
