### ISSUE TITLE
less somearchive.tar.zst throws error

### ISSUE THREAD

**Issue by solsticedhiver** [wofr06/lesspipe.sh#44]
When trying to view a .tar.zst, less (and lesspipe) throws an error:

    less somearchive.tar.zst 
    zstd: error 11 : Parameter is out of bound 
    zstd: error 11 : Parameter is out of bound 
    "/some/path/somearchive.tar.zst" may be a binary file.  See it anyway? 

I fixed that by removing the memory limits of `zstd` command in `lesspipe.sh`

```
--- lesspipe.sh	2020-08-24 14:16:40.966293679 +0200
+++ lesspipe.sh	2020-08-24 14:16:36.786244411 +0200
@@ -330,7 +330,7 @@
        *.txz) filen="${filen%.txz}.tar";;
       esac
     elif [[ "$1" = *Zstandard\ compressed* ]] && cmd_exist zstd; then
-      cmd=(zstd -cdqM4294967295 "$2")
+      cmd=(zstd -cdq "$2")
       if [[ "$2" != - ]]; then filen="$2"; fi
       case "$filen" in
        *.zst) filen="${filen%.zst}";;

```

The error might due to improper use of the argument on cli. I don't know much more.

**Comment by Konfekt** [comment]
Thank you! I applied your suggested fix.

**Comment by solsticedhiver** [comment]
Ooops. I just noticed there was already a commit 24c3676817fb8e879e7e3e185ed42182c08bf558 that fixes that.

I was running 1.84, and the commit is only in git, I guess. That commit fixes this issue.

You can revert my "fix" if you wish. May it's time for a release ? Or a bug fix release ?

Sorry.

**Comment by Konfekt** [comment]
Okay, I reverted it.
