### ISSUE TITLE
zip files being treated as office 2007 docs

### ISSUE THREAD

**Issue by jahlborn** [wofr06/lesspipe.sh#45]
the latest version seems to be broken with regards to zip files.  the filetype() function is returning "Microsoft Office 2007" for all zip files (the filecmd value is "Zip archive data, at least v1.0 to extract").

**Comment by jahlborn** [comment]
note, the issue seems to be on https://github.com/wofr06/lesspipe/blob/lesspipe/lesspipe.sh#L159, which calls all zip files office 2007 files.

**Comment by Konfekt** [comment]
Thank you for pointing this out!

**Comment by andreineculau** [comment]
Is it possible to create a 1.86 release that would include this fix? Thanks!

**Comment by Konfekt** [comment]
Out now.
