### ISSUE TITLE
Generated lesspipe.sh: Unexpected token errors

### ISSUE THREAD

**Issue by lyndhurst** [wofr06/lesspipe.sh#46]
Hi, I am trying to install `lesspipe.sh` on a recent VM with KDE neon installed:

> Operating System: KDE neon 5.19
> KDE Plasma Version: 5.19.5
> KDE Frameworks Version: 5.73.0
> Qt Version: 5.15.0
> Kernel Version: 5.4.0-47-generic

- After cloning the repository and 'cd-ing' into it, I run `./configure --yes`, it seems successful.
  - [command output](https://gist.github.com/lyndhurst/75dc1f3894effd00d7b9338efb952ef9)
  - [lesspipe.sh generated](https://gist.github.com/lyndhurst/f37e788cdf39947f3f0db01382fcb2f8)
- I copy the relevant files to `/usr/local/bin/` and set the environment variables as instructed:

```
$ ls -l /usr/local/bin/
total 264
-rwxr-xr-x 1 root root 200885 sept. 14 15:14 code2color
-rwxr-xr-x 1 root root  34972 sept. 14 15:14 lesspipe.sh
-rwxr-xr-x 1 root root  11313 sept. 14 15:14 sxw2txt
-rwxr-xr-x 1 root root   4865 sept. 14 15:14 tarcolor
 
$ echo $LESS
-R

$ echo $LESSOPEN
|/usr/local/bin/lesspipe.sh %s
```

- I try to display files with `less`, and, it gives me the following error message:

> /usr/local/bin/lesspipe.sh: line 605: syntax error near unexpected token `fi'
>
> /usr/local/bin/lesspipe.sh: line 605: `      fi'

- Trying the same process described with `./configure --default` instead gives me a different error:
  - [command output](https://gist.github.com/lyndhurst/eedcc0153da1f93f1fd8dc8dd5d8d82d)
  - [lesspipe.sh generated](https://gist.github.com/lyndhurst/fe13637468bd4a31b3e747b13ce12b61)

> /usr/local/bin/lesspipe.sh: line 793: syntax error near unexpected token `elif'
>
> /usr/local/bin/lesspipe.sh: line 793: `      elif cmd_exist code2color &&'

I tried the process described with both `bash` and `zsh`. I also tried to set `LESSCOLORIZER` to `pygmentize` for the same result. So, I would like to know if there is anything else I should do differently in order to make it work, or if there is an error in the generated file.

Thank you for your time.

**Comment by Konfekt** [comment]
The file `lesspipe.sh.in` was neglected and produced indeed invalid syntax in `lesspipe.sh`. Please check with the latest commit.

**Comment by lyndhurst** [comment]
The `./configure --yes` command gives me the following error:

> /usr/local/bin/lesspipe.sh: line 1006: syntax error near unexpected token `}'
>
> /usr/local/bin/lesspipe.sh: line 1006: `}'

On the bright side, the `./configure --default` option seems to work fine )

**Comment by Konfekt** [comment]
Yes, there was a `fi` missing. Please check again.

**Comment by lyndhurst** [comment]
It is fixed on my side, I do not get error messages anymore.

I cannot confirm if it is working though since I obviously never managed to make it work (yet), and I still do not get any highlighting. On the other hand, I am now able to display a PDF as text in terminal which I cannot without `lesspipe`, so I guess it is at least partially working for me.

Thank you.

**Comment by Konfekt** [comment]
Some code2color and friends neither worked for me; that's why I added support for [bat](https://github.com/sharkdp/bat) which does the job just fine.

**Comment by Konfekt** [comment]
Thank you for having so meticulously and politely pointed out these oversights!

**Comment by lyndhurst** [comment]
Thank you for the tip about bat, I only knew about pygment being supported.
And, you are welcome )
