### ISSUE TITLE
Help with markdown display and...iterm2?

### ISSUE THREAD

**Issue by mathomp4** [wofr06/lesspipe.sh#48]
All,

I'm hoping there is something simple I'm doing wrong. Namely, something...weird is happening when I try and `less README.md` or other markdown files. When I do so I see:
<img width="1382" alt="Screen Shot 2020-11-22 at 2 06 12 PM" src="https://user-images.githubusercontent.com/2982494/99914527-fe380700-2ccb-11eb-8f72-26fe73d27f72.png">
My reading of `lesspipe.sh` seem to say that it'll use `mdcat` if found, and well, that is in my path, and when I try to render with `mdcat README.md`:
<img width="1382" alt="Screen Shot 2020-11-22 at 2 06 56 PM" src="https://user-images.githubusercontent.com/2982494/99914553-20ca2000-2ccc-11eb-8878-06690bfe3f63.png">
A Google search for "1337 SetMark" seems to indicate it's an iTerm2 thing and I've tried turning on and off the "Show mark indicators" in my iTerm2 preferences but no change with lesspipe (though I do see the wee triangles disappear).

Any ideas on how to prevent this weirdness with lesspipe and iterm2?

**Comment by wofr06** [comment]
Dear Matthew,

I do not have a Mac, therefore I cannot reproduce what you describe. However according to the man page of mdcat it could be you have to set the env variable LESS to include at least the option -R (export LESS=-R). To me it looks like ASCII sequences are sent but not decoded.

If this does not help, please try other things mentioned in the man page of mdcat.

Best regards, Wolfgang

**Comment by anaraven** [comment]
I had the same issue (iTerm2 in Mac) and I solved it by doing

    export  LESSANSIMIDCHARS='0123456789;[?!"\'#%()*+ SetMark'

This tells `less` to use the extended "ANSI" codes

**Comment by mathomp4** [comment]
> I had the same issue (iTerm2 in Mac) and I solved it by doing
> 
> ```
> export  LESSANSIMIDCHARS='0123456789;[?!"\'#%()*+ SetMark'
> ```
> 
> This tells `less` to use the extended "ANSI" codes

Holy...how did you figure that out?! 😲 

I'll give it a try soon...once I can remember if it was my home Mac or work Mac that had the issue!

**Comment by anaraven** [comment]
> Holy...how did you figure that out?! 😲

I remembered that `less` used either `-R` or `-r` to show "raw codes". Looking at the man page it offered this environment variable as a way to use `-R` for "some" codes. Then I googled to find the default values.

Good luck finding your Mac

**Comment by Aaron-Rumpler** [comment]
@wofr06 Maybe `lesspipe` should pass the `--ansi` option to `mdcat`? According to the man page, this disables any terminal-specific features (none of which would are passed through by `less` with `--RAW-CONTROL-CHARS` anyway).

**Comment by wofr06** [comment]
I give it a try. Should help according to the docs.
