### ISSUE TITLE
Allow passing options to pygmentize

### ISSUE THREAD

**Issue by anntzer** [wofr06/lesspipe.sh#5]
pygmentize's output, and in particular its choice of colors, can be controlled by various flags (e.g `pygmentize -fterminal256 -Ostyle=monokai`).  It would be nice if it was possible to pass this kind of flags through lesspipe.
I'd guess introducing a new environment variable `LESSPYGMENTIZEOPTIONS` should maintain the current safety checks.

**Comment by wofr06** [comment]
On Fri, 15 Jan 2016, Antony Lee wrote:

> pygmentize's output, and in particular its choice of colors, can be 
> controlled by various flags (eg pygmentize -fterminal256 
> -Ostyle=monokai) It would be nice if it was possible to pass this kind 
> of flags through lesspipe I'd guess introducing a new environment 
> variable LESSPYGMENTIZEOPTIONS should maintain the current safety checks

I dislike the idea of an inflation of ENV variables. I propose to weaken 
the test in code2color to accept both a full PATH for pygmentize and 
options as long as they do contain a subset of chars (wordchars, = and -)

## I will try to make these changes soon.

Best regards
Wolfgang

**Comment by kergoth** [comment]
This would be lovely, I ended up patching code2color to accept another colorizer which is just a wrapper around pygmentize that obeys a couple env vars as a stopgap measure.

**Comment by pszynk** [comment]
+1

**Comment by dcsobral** [comment]
Oh, wow, this is still open? I also need this feature. Code2color does not support the languages I work with, and pygmentize default formatter looks bad on my terminal.

**Comment by mortenlj** [comment]
This works on funtoo/gentoo, so I was surprised to see that I couldn't add options to pygmentize when I got a new Mac for work. Looking more closely, it seems gentoo has it's own version of lesspipe. 😞

**Comment by Konfekt** [comment]
> On Fri, 15 Jan 2016, Antony Lee wrote:
> 
> > pygmentize's output, and in particular its choice of colors, can be
> > controlled by various flags (eg pygmentize -fterminal256
> > -Ostyle=monokai) It would be nice if it was possible to pass this kind
> > of flags through lesspipe I'd guess introducing a new environment
> > variable LESSPYGMENTIZEOPTIONS should maintain the current safety checks
> 
> I dislike the idea of an inflation of ENV variables. I propose to weaken
> the test in code2color to accept both a full PATH for pygmentize and
> options as long as they do contain a subset of chars (wordchars, = and -)
> ## I will try to make these changes soon.
> 
> Best regards
> Wolfgang

For reference, [this](https://github.com/wofr06/lesspipe/blob/c3bb06348b9364ad5e0ac177acffb5b054959b04/code2color#L3258) is the check that currently impedes passing arguments to pygmentize.

**Comment by nerd190** [comment]
@Konfekt so if I were to extend the '-g' argument that lesspipe adds to '-g -style=gruvbox' then would I finally get my own theme? I've been following this issue for **years** now.
Thank you for any advice you can give me, its really apprectiated.

**Comment by Konfekt** [comment]
Instead of `$ENV{LESSCOLORIZER} eq 'pygmentize'`, how about `basename($ENV{LESSCOLORIZER}) eq 'pygmentize` to allow passing arguments?

**Comment by Konfekt** [comment]
@5c0tt-b0t Please test latest master.

**Comment by Konfekt** [comment]
I guess there is a problem that `base` does not extract the name of the executable in case arguments are appended. I see no reliable solution other than supposing that the path to the executable does not contain any spaces.

**Comment by wofr06** [comment]
In the latest version it is now allowed to give the style option to pygmentize, maybe some more options can be added later. I do not want to introduce yet another ENV variable
