### ISSUE TITLE
filename with : do not work with lesspipe

### ISSUE THREAD

**Issue by solsticedhiver** [wofr06/lesspipe.sh#51]
Archlinux has some weird package name where there is a : being part of the name of the file like `anbox-git-1:r1324.165db5c-1-x86_64.pkg.tar`

This happens if an epoch is defined in the PKBUILD

And this fails with *lesspipe* and *less*. I don't know if you could consider this a bug.

    $ less anbox-git-1\:r1324.165db5c-1-x86_64.pkg.tar
    ==> use tar_file=contained_file to view a file in the archive
    tar: Cannot connect to anbox-git-1: resolve failed

**Comment by Konfekt** [comment]
This is because of 

```sh
# lesspipe.sh (line 55)
sep=:						# file name separator
```

in case of `lesspipe`. I suppose less uses the same file name separator.

**Comment by wofr06** [comment]
Sorry that I did not close the issue. This behaviour was a bug and I corrected it two weeks ago. It should work now.
