### ISSUE TITLE
how to not include "lesspiped" attachements in reply?

### ISSUE THREAD

**Issue by alembiq** [wofr06/lesspipe.sh#53]
is there a way how to configure mutt, to include original email in the reply, and not use the one converted by lesspipe?   
imagine having a book in a PDF as an attachement and replying to that.... :(

**Comment by wofr06** [comment]
I am not using mutt, but according to the documentation you could do the 
following:

1) set the $pager variable to "builtin"
2) set the $pager variable to "LESSOPEN= /usr/bin/less"   (if less is in 
/usr/bin. The space is important)
3) if 2) does not work, write a wrapper script for less where you call 
less after you issued an 'unset LESSOPEN'

Does this solve your problem?

Am 13.04.21 um 12:17 schrieb Karel Křemel:

**Comment by Konfekt** [comment]
> imagine having a book in a PDF as an attachement and replying to that.... :(

For this case, add

```sh
application/pdf;                   pdftotext -l 10 -nopgbrk -q  -- %s -; nametemplate=%s.pdf; copiousoutput
```

where `10` is the number of paged pages.
