### ISSUE TITLE
less *.png shows nonsense

### ISSUE THREAD

**Issue by savchenko** [wofr06/lesspipe.sh#54]
Using 8267f2f:

```
$ less PNG_demo_Banana.png
IHDR
IDATx
n-,I
5Ve(m
4XS!
AtPS
53-'
-i%hi%N
G?*g
...
```

![image](https://user-images.githubusercontent.com/300146/117565488-b9285580-b0f0-11eb-8bba-f6253bcbcfa8.png)

File in question: https://upload.wikimedia.org/wikipedia/commons/c/ce/PNG_demo_Banana.png

**Comment by Konfekt** [comment]
Please try the latest commit.

**Comment by Konfekt** [comment]
... and thank you for letting us know!

**Comment by savchenko** [comment]
Perfect! 

![image](https://user-images.githubusercontent.com/300146/117897836-c2890c00-b302-11eb-8aa1-d7a319771621.png)

**Comment by wofr06** [comment]
The fix was not correct. Redone. Reordered programs tried according to content displayed (mediainfo before exiftool before identify).
