### ISSUE TITLE
JSON files erroneously treated as binary

### ISSUE THREAD

**Issue by jerith666** [wofr06/lesspipe.sh#62]
```
$ cat test.json 
{
  "hello": {
    "world": [
      true,
      false
    ]
  }
}

$ lesspipe.sh test.json 
==> append : to filename to view the raw data
  "hello": {
    "world": [
      true,
      false
    ]
```

This seems to be because:

```
$ file test.json 
test.json: JSON data
```

... and it falls into the "data" catch-all at https://github.com/wofr06/lesspipe/blob/lesspipe/lesspipe.sh.in#L1228.  See also https://github.com/wofr06/lesspipe/commit/18bbe1de1a870985cbbeda30b3cee50473fafa24.

**Comment by wofr06** [comment]
Yes, json was added recently fpr Jupyter notebooks only, but the output 
of pandoc in this case is not much different:
{ “hello”: { “world”: [ true, false ] } }
Maybe one could add such a clause.

Thanks for your input

Am 13.10.21 um 15:39 schrieb Matt McHenry:

**Comment by wofr06** [comment]
According to my test suite this seems to be fixed in the latest git
