### ISSUE TITLE
docx2txt.pl --> docx2txt

### ISSUE THREAD

**Issue by savchenko** [wofr06/lesspipe.sh#65]
Given that Perl version wasn't updated since ~2009, it might be worth switching to https://github.com/ankushshah89/python-docx2txt

Latter is available via `pip`.

**Comment by wofr06** [comment]
I do agree with the name change (without the .pl). However the docx2txt that is contained in Ubuntu is still a perl version (from 2014). The python version should accept a minus sign both for STDIN and STDOUT to be compatible with the perl version
