### ISSUE TITLE
Install to `~/.local` by default

### ISSUE THREAD

**Issue by savchenko** [wofr06/lesspipe.sh#66]
Will make life easier for those working without `root` rights. From an end-user perspective, experience should be the same.

**Comment by wofr06** [comment]
The usual sequence of commands to install software is
configure; make;make install where the last step might require super user rights.
Also most configure scripts like that for this lesspipe do have the --prefix option.
Using ./configure --prefix=~/.local --yes would install lesspipe.sh in ~/.local/bin, which is what you requested.
Therefore I would not try to change the defaults
