### ISSUE TITLE
Remove forced bat theme

### ISSUE THREAD

**Issue by adrianlzt** [wofr06/lesspipe.sh#67]
In commit 75c488dc9fdad31d26bc46b0607772ac6b2a4ec7 this line was added:
```
bat_theme='--theme GitHub'
```

Forcing that particular bat theme.

Maybe that was an error? I guess is more user friendly to let the user chose its theme in the bat configuration.

**Comment by wofr06** [comment]
In the latest git version that is removed again. I have seen that bat has a config file...
