### ISSUE TITLE
Compressed ppd files (*.ppd.gz) are not displayed as text but as binary

### ISSUE THREAD

**Issue by callegar** [wofr06/lesspipe.sh#72]
Would be handy to be able to see ppd (postscript printer description) files as text.

**Comment by wofr06** [comment]
All my tests show, that this is handled properly. I only can imagine a system with a broken file cmd (what does file  and file -i report) or the unlikely case that gzip is not available on the system

**Comment by callegar** [comment]
The issue does not appear to be the .gz (gzipped text `.txt.gz` files are handled properly), but the fact that this is a gzipped *ppd* file. Maybe the report from file is not dealt with correctly.

on the ppd.gz, `file` reports `/usr/share/ppd/HP/hp-tango.ppd.gz: gzip compressed data, from Unix, original size modulo 2^32 27878` and `file -i` gives `/usr/share/ppd/HP/hp-tango.ppd.gz: application/gzip; charset=binary`... But maybe the issue is what `file` reports on the uncompressed ppd, that is `PPD file, version "4.3"` and `text/plain; charset=us-ascii`

**Comment by wofr06** [comment]
I downloaded hplip-3.21.12.tar.gz and with the version 2.00 lesspipe.sh I could both display the contents of the unpacked hplip-3.21.12/ppd/hpcups/hp-tango.ppd.gz as well as directly from the archive:
hplip-3.21.12.tar.gz:hplip-3.21.12/ppd/hpcups/hp-tango.ppd.gz
There might have been an issue with earlier versions of lesspipe.sh
