### ISSUE TITLE
Bat error with files of unknown syntax in *.d directories

### ISSUE THREAD

**Issue by schance995** [wofr06/lesspipe.sh#75]
Using lesspipe with bat on a file in a .d directory causes bat to throw an error.
```zsh
% less /etc/tlp.d/README
[bat error]: unknown syntax: 'd/README'
```
This fails with exit code 1:
```zsh
% lesspipe.sh /etc/tlp.d/README
[bat error]: unknown syntax: 'd/README'
```
These work as expected (no errors thrown)
```
% less /etc/tlp.d/00-template.conf 
% lesspipe.sh /etc/tlp.d/00-template.conf
% bat /etc/tlp.d/README
% bat /etc/tlp.d/00-template.conf 
```

**Comment by wofr06** [comment]
bat/batcat uses the -l language flag now only if set explicitly, i e. with e.g. 
less filename:lang Additional tests are performed to not call bat with a wrong language.
