### ISSUE TITLE
UTF-8 text on FreeBSD

### ISSUE THREAD

**Issue by elfham** [wofr06/lesspipe.sh#76]
When opening UTF-8 text in FreeBSD, a warning will appear.

```
% cat utf8.txt
あいうえお
% less utf8.txt

==> append :: to filename to view the utf-8 encoded file
あいうえお
utf8.txt (END)
```

https://github.com/wofr06/lesspipe/blob/lesspipe/lesspipe.sh#L718
``` bash
lclocale=$(echo ${locale##*.}|sed 's/\(.*\)/\L\1/')
```

Here `$lclocale` is set to "LUTF-8" instead of "utf-8".

Since `\L` is not a standard, but an extension of GNU sed, it is better to use `tr` or something similar instead.

**Comment by wofr06** [comment]
Thanks, just changed conversion from sed to tr
