### ISSUE TITLE
Syntax highlighting with code2color and vimcolor not working.

### ISSUE THREAD

**Issue by 0xAF** [wofr06/lesspipe.sh#77]
`lesspipe.sh` calls `code2color` with `-l LANG` argument.
For Perl script it becomes `-l pl`, for Python it becomes `-l py`.
These are not correct values for `-l` parameter of `code2color`, it expects `-l perl` and `-l python`.

Here is the defined language key for Perl in `code2color`:
https://github.com/wofr06/lesspipe/blob/lesspipe/code2color#L1670

And here is how `lesspipe.sh` prepares the command for `code2color`:
https://github.com/wofr06/lesspipe/blob/lesspipe/lesspipe.sh#L407

The same happens with `vimcolor`. Working with `-l perl`, but not working with `-l pl`.
I'm not sure where the `-l` argument is prepared for `vimcolor`, since I haven't follow the logic of the `lesspipe.sh` script to find it.

**Comment by wofr06** [comment]
Changed the calling behaviour for code2color and vimcolor. The programs get called with the -l flag only if language forced by a :language_type appended to the filename
