### ISSUE TITLE
[Question] LESSCLOSE

### ISSUE THREAD

**Issue by gerardbosch** [wofr06/lesspipe.sh#79]
Hi there, just a question here :)

The "original" `lesspipe` that comes pre-installed, for example in Ubuntu, also sets the `$LESSCLOSE` env variable:

```console
❯ /usr/bin/lesspipe
export LESSOPEN="| /usr/bin/lesspipe %s";
export LESSCLOSE="/usr/bin/lesspipe %s %s";
```

I don't see in this project's README or Wiki anything related to `$LESSCLOSE`, so isn't required to be set? I'm not very sure what's the goal of LESSCLOSE, maybe do cleanup on compressed files?

Thanks!

**Comment by wofr06** [comment]
No, LESSCLOSE is not required/useful here. Just a quote from the man page of less: "When an input pipe is used, a LESSCLOSE postprocessor can be used,  but  it is usually not necessary since there is no replacement file to clean up."

**Comment by gerardbosch** [comment]
Cool, thank you!
