### ISSUE TITLE
Add support for jar files

### ISSUE THREAD

**Issue by ketan** [wofr06/lesspipe.sh#8]
```
$file -L -s target/libs/agent-16.3.0-standalone.jar
target/libs/agent-16.3.0-standalone.jar: Java archive data (JAR)
$ file -L -s -i target/libs/agent-16.3.0-standalone.jar
target/libs/agent-16.3.0-standalone.jar: application/java-archive; charset=binary
```

Apprarently lesspipe is unable to handle this, however tweaking the `filetype` function to add another or clause for zip files seems to fix the problem — 

```
elif [[ ("$type" = *Zip* || "$type" = *ZIP* || "$type" = *JAR*) && ("$name" = *.jar || "$name" = *.xpi) ]]; then
```

**Comment by samlii** [comment]
@ketan I don't know if you still are monitoring this, but I was curious what version of file it was and what os you were using.

**Comment by htgoebel** [comment]
I have file-5.37 and this reports JAR files as described above.
