### ISSUE TITLE
Suggestion: some helper tools for pretty displaying plain text csv or tsv tabular data files

### ISSUE THREAD

**Issue by m040601** [wofr06/lesspipe.sh#80]
Here is an additional suggestion for making viewing the ubiquous csv/tsv files on the terminal more confortable. Thanks in advance.

"Pretty" here means either "with color" and/or display the columns nicely aligned .

Currently we have this with lesspipe (correct me if wrong):

For csv or tsv tabular files **_that are already plain text,_** lesspipe falls back to bat or to a python/perl colorizer:

````
for i in bat batcat pygmentize source-highlight code2color vimcolor ; do
                bat|batcat)
````

The "colorizer" basicly does only that, it  adds color.
This is very usefull for viewing csv files, each column gets a different color.
But it doesnt reformat the file. It doesnt align the colums, which can also be nice and confortable for viewing.

There is  however a plethora of simple unix friendly tools, that do this "reformat" (and/or also color). They are easily combined in pipes  for use with  a pager helper:

1. https://strahinja.srht.site/table

- super unix friendly, GNU c

2. https://github.com/BurntSushi/xsv

- rust, very famous, "xsv table file.csv" outputs to stdout

3. https://github.com/alexhallam/tv

- go, recent tool, not battle tested, "cat file.csv | tv" seems to output to stdout

4. Many others I can't remember now

PS: Related

Currentyl for "binary" spreadsheet like formats (xls, ods, etc) lesspipe uses:

````
ods requires xlscat or libreoffice
...
Excel (xlsx) requires in2csv or xlscat or excel2csv or libreoffice
...
````

Those tools first convert the "binary" file to a plain csv like text file that less can them display.

**Comment by gerardbosch** [comment]
This could be nice combined with horizontal scrolling in less `less -S`, as CSV files tend to be wide.
Would it be possible to pass the `-S` flag to less when dealing with these kind of files?

**Comment by wofr06** [comment]
I looked at a few of these tools, all do assume a comma (or tab for tsv) as a delimiter as the name and also the RFC suggests. However there are many tools that do output csv like formats with a different delimiter. This is often used to avoid quoting, e.g. in address lists containing name, firstname in one field. Those files would then be displayed incorrectly (plain display possible with appended colon) 
The program 'table' does shorten the fields to fit in 80 columns. I did not find an option to display the whole table with the minimum number of columns. To use git to download and then to compile the tool is an additional complication that not all users will be able to manage, which applies also to the other proposed programs.
An option that does not add new programs would be to use pandoc for display with a fallback to csvlook. The latter is at least on Ubuntu in the same package as in2csv. Would that make sense?

**Comment by gerardbosch** [comment]
Hi there, not sure if this can help to the conversation:

I've just quickly tested `xsv` (e.g. I did `brew install xsv` on Linux), and it seems flexible to specify delimiters before reading a CSV:

```console
xsv input --delimiter '=' equals-delimited-file.csv | xsv table | less -S
```
I guess that doing this way it would be an extra dependency users would need to install like `in2csv`, `libreoffice` or other tools `lesspipe.sh` relies on. That can also be installed in both Linux/macOS at least with Brew and Nix: `nix profile install nixpkgs#xsv` :)

I didn't use pandoc before ever, can it be used to convert CSV to formatted table? 
Sure! it makes total sense to reuse the same tools and not requiring extra stuff to be installed, if that can be achieved, hehe.

**Comment by wofr06** [comment]
Well, except for pandoc the other tools also do allow to specify delimiter characters, but that does not help, as it is not automatic. But this is probably not a big issue, as with an appended colon you see the original.
For me the csvlook output looks a bit better and is not such a heavy tool as pandoc, so I will change the calling order. Changing a less option within less is not possible. But you can type -S followed by Enter to get horizontal scrolling after less has started.

**Comment by Strahinja** [comment]
> The program 'table' does shorten the fields to fit in 80 columns. I did not find an option to display the whole table with the minimum number of columns.

Not the one who submitted the proposal, but as I'm the author of the program **table**(1) I felt compelled to join the conversation. As stated in the manual page (`man table` when installed), **table** has several command line options, some of which are:
```
       -d delim
       --delimiter=delim
              Set field delimiter (default ","). First line of the input determines the number of table columns. Special characters, like ";", need to be quoted:

                   $ table -d ';'
```
and
```
       -c cols
       --columns=cols
              Set maximum table width in columns (default 80).
```
Also `table -h` gives a quick option summary.

**Comment by wofr06** [comment]
Yes, I read that. To make use of -c columns one needs to know how many columns are minimally required to not truncate the csv contents. Setting it to a large value enlarges the fields over the required minimum.

**Comment by Strahinja** [comment]
This (current?) limitation of **table** comes from how the program handles its input. The input is read and output line-by-line. In order to compute the maximal width of a column, it would need to either a) read up and store the entirety of its input in memory, or b) read its input twice, which would be susceptible to errors if the input changes, and wouldn't work in the general case when reading from stdin. Currently, it is not as dependant on memory as it would be were it to buffer its input.

**Comment by wofr06** [comment]
I just committed changes in the direction of your proposal. I tested with a few files, it seems to work as suggested. Please report cases where this solution is not satisfactory.
