### ISSUE TITLE
Help with lesspipe: no colorizing

### ISSUE THREAD

**Issue by mathomp4** [wofr06/lesspipe.sh#83]
I apparently am an idiot as I can't figure out what I'm doing wrong.

So, I want to use `bat` to colorize with lesspipe. So, in my environment I have set:

```console
❯ env | grep LESS
LESS=-fRimWFX
LESSOPEN=|/usr/local/bin/lesspipe.sh %s
LESS_ADVANCED_PREPROCESSOR=1
LESSCOLORIZER=bat --style=plain
```

I like the `bat` plain style, and my lesspipe is v2.04 from brew.

As far as I know, this is all good...but when I call `less`, it's not using `bat` at all. Just...something not colorful. I see something from lesspipe it looks like with the "append" message:

```console
❯ less CHANGELOG.md
==> append : to filename to view the markdown file
Changelog

All notable changes to this project will be documented in this file.

The format is based on Keep a Changelog, and this project adheres to
Semantic Versioning.
...
```

The weird thing is, I think I have pretty much the same settings on another laptop and it works. (Well, on that one I'm experimenting with using `pygmentize`, but still, I get color!).

Any ideas of my mistake?

**Comment by wofr06** [comment]
The handling of the -l option for bat was slightly improved like in #77. The option for bat in the ENV variable LESSCOLORIZER  is ignored. bat can be configured using ~/.config/bat/config.
LESS_ADVANCED_PREPROCESSOR is not used anymore.
Nevertheless I could not reproduce your problem, for me the files do show colors also with bat.

**Comment by mathomp4** [comment]
Okay. I decided to do a big ol' clean of my setup and I think I got it working! Thanks!
