### ISSUE TITLE
`make install` ignores PREFIX for less_completion

### ISSUE THREAD

**Issue by kc9jud** [wofr06/lesspipe.sh#89]
Output:
```
> make install
mkdir -p /global/homes/p/pfasano/opt/cori/bin
mkdir -p /global/homes/p/pfasano/opt/cori/share/man/man1
mkdir -p /global/homes/p/pfasano/opt/cori/share/zsh/site-functions
mkdir -p /etc/bash_completion.d
cp ./code2color ./sxw2txt ./archive_color ./lesspipe.sh ./vimcolor ./lesscomplete /global/homes/p/pfasano/opt/cori/bin
cp ./lesspipe.1 /global/homes/p/pfasano/opt/cori/share/man/man1
cp ./less_completion /etc/bash_completion.d
cp: cannot create regular file '/etc/bash_completion.d/less_completion': Permission denied
make: *** [Makefile:17: install] Error 1
```

Note that lines 59 and 62 of `configure` are missing `\$(PREFIX)`:
https://github.com/wofr06/lesspipe/blob/ff563f0825fa1604e69ea9ad5c42b33d4815a415/configure#L55-L62

**Comment by kc9jud** [comment]
A note in `INSTALL` might be useful about how to set up completions in a non-standard place: https://github.com/scop/bash-completion/blob/master/README.md#FAQ

**Comment by wofr06** [comment]
The omission of prefix is on purpose, as the completion script needs to be loaded statically. The proposed locations in the aforementioned README are for dynamic loading, which seems not to work (for me in Ubuntu). When generating the Makefile, a prefix is respected, if it does not start with /usr. Then a warning is issued.

**Comment by kc9jud** [comment]
I don't see any warning when running `./configure --prefix=/global/homes/p/pfasano/opt/cori` -- what should I be seeing? The generated makefile also exits unsuccessfully before setting permissions on `lesspipe.sh`, so it's not even something where I can just ignore the broken bash completion. (Of course, I can just set the permissions myself, but then I probably shouldn't use the makefile at all.)

**Comment by wofr06** [comment]
The Makefile is generated now with a warning when using a prefix.

>installing bash completion in `$PREFIX/`share/bash-completion
 In bash, please preload the completion, dynamic invocation does not work
. `$PREFIX`/share/bash-completion

where `$PREFIX` is replaced with the content of this variable
