### ISSUE TITLE
code2color: support Gentoo files as shell scripts

### ISSUE THREAD

**Issue by vapier** [wofr06/lesspipe.sh#9]
the code2color program supports highlighting shell scripts based on extension.  can we include Gentoo files in there too ?

``` perl
 $LANGUAGE{'shellscript'} = {
-   'filename' => '\\.(sh|shell)$',
+   'filename' => '\\.(ebuild|eclass|sh|shell)$',
```

**Comment by wofr06** [comment]
Finally added, sorry for the long delay
