### ISSUE TITLE
lesspipe.sh only tests for short command line options

### ISSUE THREAD

**Issue by gdevenyi** [wofr06/lesspipe.sh#93]
These two LESS variables are equivalent:

The first here, lesspipe.sh produces no output
`export LESS='--quit-if-one-screen --ignore-case --status-column --LONG-PROMPT --RAW-CONTROL-CHARS --HILITE-UNREAD --tabs=4 --window=-4'`

The second here, it works as expected:
`export LESS='-F -i -J -M -R -W -x4  -z-4'`

Found playing with https://www.topbug.net/blog/2016/09/27/make-gnu-less-more-powerful/

**Comment by wofr06** [comment]
A fix has been provided
