### ISSUE TITLE
A few suggestions (per the use on Cygwin)

### ISSUE THREAD

**Issue by al20878** [wofr06/lesspipe.sh#94]
Hi,

First off, thanks a lot for making this tool available for the community!
There are a few things I would like to bring to your attention regarding the use of it on Cygwin:

1. `configure`
```
$ ./configure
zsh not found in the PATH
$
```
It left me baffled at first, as to whether that actually failed or not (until I checked the exit code and it turned out to be 0).  But it did find `bash` so everything was fine, in the end...  So suggested is to elaborate, either in that message (like, adding "continuing"), or printing a final message that the configuration succeeded. (I checked the source: it prints a failure message when no suitable shells have been found, so why not on success?)

2. `test.pl`
It outputs
```
ps: unknown option -- T
Try `ps --help' for more information.
```
with every test it runs...  Cygwin has two versions of "`ps`" -- one is rather abridged (comes in the "base package" and is native to Cygwin) and does not have the "`-T`" option; and the other one is (in an optional package) called "`procps`", which is based on the `/proc` filesystem, and is more or less standard with the set of options, `-T` included (for threads).  Judging by most of the tests passing even with that noise from `ps` I wonder, whether `-T` is actually required to use?  Or if it is desired, can it first be checked for validity, and then only used conditionally?

Also, I tried to invoke a usage message by running `./test.pl`  with some "guessable" options, like `-h`, `--help`, but neither worked, so I had to look into the source code for the `usage` subroutine:

```
$ ./test.pl -h
testing ./lesspipe.sh
93 ignore  C language (source-highlight) git #3 (needs source-highlight)
0/1/0 tests passed/ignored/failed in 0 seconds
$ ./test.pl --help
testing ./lesspipe.sh
0/0/0 tests passed/ignored/failed in 1 seconds
```
My only luck was with `-?` but that's rather limiting because in some shells (C-shells) the bare question mark invokes globbing, and then fails even before launching the command (so it's not widely remembered as a safe choice for help, because you have to type it escaped as `-\?` to work properly).

3. `Makefile`
Even though `zsh` wasn't found, `Makefile` still attempts to copy all the `zsh` stuff for installation.  Why?  Shouldn't those be skipped?
```
....
        mkdir -p $(DESTDIR)$(PREFIX)/share/zsh/site-functions
...
        cp ./_less $(DESTDIR)$(PREFIX)/share/zsh/site-functions
...
```

4. `lesspipe.sh`
When I try to open a file, for which `lesspipe.sh` was called, I see the same `-T` error that I saw in testing (maybe it wasn't a `test.pl`'s feature in there all along but `lesspipe`'s?):
```
ps: unknown option -- T
Try `ps --help' for more information.
```
Nonetheless the contents seem to be processed correctly.  The question again, if the `-T` is at all necessary or can it be used conditionally?  (I edited `/usr/local/bin/lesspipe.sh` to replace `ps` with `procps` in `analyze_args()` to get rid of the noise.)

5. Lastly, there are 6 tests failed in my case, but many were skipped, here's the summary:
```
...
55 NOT ok  UTF-16 Unicode
           failing command: less tests/filter.tgz:test_utf16
...
56 NOT ok  ISO-8859-1 encoded file
           failing command: less tests/filter.tgz:test_latin1
...
90 NOT ok  directory
           failing command: less /tmp/lesspipeHDvG/tests
...
96 NOT ok  even colorize piped files
           failing command: cat /tmp/lesspipeHDvG/tests/test.c|less - :c
...
118 NOT ok  extract files from piped file
           failing command: cat /tmp/lesspipeHDvG/tests/test_zip|less - :tests/test.tar
...
119 NOT ok  extract files from piped archive
           failing command: cat /tmp/lesspipeHDvG/tests/test_zip|less - :tests/test.tar:tests/textfile
...
76/42/6 tests passed/ignored/failed in 70 seconds
```
I wonder if the failing commands have to do anything with the colon `':'` in the file names (except for 90 and 96) that is causing Windows filesystem to misbehave...
But it looks like the failing tests are not affecting `lesspipe` for what I am using it with, which are mostly the archives.

Thanks!

**Comment by wofr06** [comment]
The treatment for a missing shell in configure has changed. This covers suggestions 1) and 3). The errors reported in problems 2), 4) and 6) are due to the ps command that does not output the arguments that were given to the less command. The more advanced features of lesspipe therefore do not work. Deleting the lines in lesspipe.sh where the cmdtree variable gets evaluated and setting lessarg to the empty string there would prevent the error messages in Cygwin.
