### ISSUE TITLE
Print name of program in messages

### ISSUE THREAD

**Issue by Mathnerd314** [wofr06/lesspipe.sh#98]
I was confused for quite a while as to why `less test.md` wasn't showing the contents literally. The only message is this:
```
==> append : to filename to view the markdown file
```
It turns out lesspipe is enabled by default in NixOS. I suggest a little banner like so:
```
==> processed via lesspipe v2.06
==> append : to filename to view the original markdown file
```
to explain what's happening more clearly and give something to google.

**Comment by Mathnerd314** [comment]
As far as implementation something like:
```
msg () {
	[[ -n "$LESSQUIET" ]] && return;
        if [[ -z "$banner" ]]  then
                echo "==> processed by lesspipe v2.06"
                banner=y
        fi
	echo "==> $*"
}
```
but I don't know bash that well.
And [here](https://github.com/wofr06/lesspipe/blob/917c23577259a5e79e71db6ec3ec776b92d7c673/lesspipe.sh#L559) it is just adding the word original:
```
		[[ -z $msg ]] && msg="append $sep to filename to view the original $x file"
```

**Comment by wofr06** [comment]
I hesitate to produce more than one line by default. Therefore I did not output the line "processed by lesspipe v2.06", the other change is done.

**Comment by Mathnerd314** [comment]
I still want the name of the program. Could you do `msg="lesspipe: append $sep to filename to view the original $x file"`? It's on one line.

**Comment by wofr06** [comment]
Did you pull the latest version? I did include the name and version in the message.

04.01.2023 04:53:25 Mathnerd314 ***@***.***>:

**Comment by Mathnerd314** [comment]
Ah no, I didn't look at https://github.com/wofr06/lesspipe/commit/ebce4ff152b90250913b1b43121cdee7de895bd4 and was just guessing based on your comment. It looks fine.
